# Configuration file
configfile: "config/config.yml"

# Global vaiables
data_dir = config["data_dir"]
samples_dir = config["samples_dir"]
samples = config["samples"]
genome = config["genome"]

# Rules
include: "rules/map_reads.smk"

rule all:
    input:  
        expand("results/mapped_reads/{sample}.sam", sample=samples)
