data_dir: /students/2022-2023/Thema11/DataprocessingTim/test_data
results_dir: /homes/tswarts/jaar3.5/Dataprocessing/eindopdracht/results
genome: dummy_genome.fna
barcode_file: barcodes.txt
read_name: dummy_reads
